<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>3.0.3</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyName>SpaceWeatherAndAtmosphericOrbitalDecay</AssemblyName>
    <RootNamespace>SpaceWeatherAndAtmosphericOrbitalDecay</RootNamespace>
    <TargetFramework>net481</TargetFramework>

    <Description>Space Weather And Atmospheric Orbital Decay (SWAOD) introduces orbital decay mechanics with Kerbalism solar storm integration.</Description>
    <Product>SpaceWeatherAndAtmosphericOrbitalDecay</Product>

    <KSPBT_ModRoot>$(ProjectRootDir)GameData\$(AssemblyName)</KSPBT_ModRoot>
    <KSPBT_ModPluginFolder>Plugin</KSPBT_ModPluginFolder>

    <LangVersion>latest</LangVersion>
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(KSPBT_ModVersion)' != '' ">
    <Version>$(KSPBT_ModVersion)</Version>
    <FileVersion>$(Version)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ModReference Include="ClickThroughBlocker">
      <DLLPath>GameData/000_ClickThroughBlocker/Plugins/ClickThroughBlocker.dll</DLLPath>
      <CKANIdentifier>ClickThroughBlocker</CKANIdentifier>
      <KSPAssemblyVersion>1.0</KSPAssemblyVersion>
    </ModReference>
  </ItemGroup>

  <ItemGroup>
    <KSPVersionFile Include=".">
      <Destination>$(KSPBT_ModRoot)/$(AssemblyName).version</Destination>
      <URL>https://github.com/Aebestach/SpaceWeatherAndAtmosphericOrbitalDecay/releases/latest/download/SpaceWeatherAndAtmosphericOrbitalDecay.version</URL>
      <Download>https://github.com/Aebestach/SpaceWeatherAndAtmosphericOrbitalDecay/releases/latest</Download>
      <KSP_Version>1.12.5</KSP_Version>
      <KSP_Version_Min>1.12.0</KSP_Version_Min>
      <KSP_Version_Max>1.12.99</KSP_Version_Max>
    </KSPVersionFile>
  </ItemGroup>

  <Target Name="DeployGameDataToKsp" AfterTargets="KSPBT_CopyDLLsToPluginFolder" Condition=" '$(KSPBT_GameRoot)' != '' ">
    <PropertyGroup>
      <_KspModDeployDir>$(KSPBT_GameRoot)/GameData/$(AssemblyName)</_KspModDeployDir>
    </PropertyGroup>
    <ItemGroup>
      <_ModDeployFiles Include="$(KSPBT_ModRoot)/**/*" />
    </ItemGroup>
    <Copy SourceFiles="@(_ModDeployFiles)" DestinationFolder="$(_KspModDeployDir)/%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Message Text="Deployed GameData to $(_KspModDeployDir)" Importance="high" />
  </Target>
</Project>
